import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:alphaserena_admin_portel/core/utils/csv_table.dart';
import 'package:alphaserena_admin_portel/core/utils/exercise_csv.dart';
import 'package:alphaserena_admin_portel/core/utils/exercise_search.dart';
import 'package:alphaserena_admin_portel/models/global_exercise_model.dart';

// ════════════════════════════════════════════════════════════════════════
// GLOBAL EXERCISE LIBRARY — the console's half of the platform contract.
//
// Three things are pinned here, and each one is load-bearing:
//
//   1. The SEARCH CONTRACT. The fixtures were generated by running the
//      backend's own `nameKey`/`searchPrefixFor`
//      (functions/src/lib/exercise_catalog.ts). If either side drifts, the
//      console computes a prefix no stored document carries and reports the
//      catalog as empty — a failure indistinguishable from "the import did
//      not work".
//
//   2. The CATEGORY VOCABULARY. The server REJECTS a row whose category is
//      not on its list, so a Dart list that has drifted would render a
//      picker whose choices the server refuses.
//
//   3. THE SHIPPED DATASET ITSELF. The 844-row CSV is a product artifact, not
//      test data. This suite parses the real file off disk through the real
//      importer and proves it would import cleanly — every row named, every
//      row in a real category, and not one duplicate. A dataset asserted by
//      eye is a dataset nobody has actually checked.
// ════════════════════════════════════════════════════════════════════════

void main() {
  group('search contract — parity with the backend', () {
    test('name keys match the backend exactly', () {
      expect(exerciseNameKey('Push-Up'), 'push up');
      expect(exerciseNameKey('  Barbell   Bench Press '), 'barbell bench press');
      expect(exerciseNameKey('Résistance Band Row'), 'resistance band row');
      expect(exerciseNameKey('Kettlebell Swing (Two-Hand)'),
          'kettlebell swing two hand');
      expect(exerciseNameKey('45-Degree Back Extension'),
          '45 degree back extension');
    });

    test('query prefixes match the backend exactly', () {
      expect(exerciseSearchPrefix('squat'), 'squat');
      expect(exerciseSearchPrefix('SQUAT'), 'squat');
      expect(exerciseSearchPrefix('  romanian deadlift '), 'romanian');
      // Longer than the stored prefix cap → truncated to it.
      expect(exerciseSearchPrefix('supercalifragilistic'), 'supercalifra');
    });

    test('a query below the minimum prefix is refused, not guessed', () {
      expect(exerciseSearchPrefix('a'), isNull);
      expect(exerciseSearchPrefix(''), isNull);
      expect(exerciseSearchPrefix('  '), isNull);
      expect(exerciseSearchPrefix('!!'), isNull);
      expect(kMinExercisePrefix, 2);
      expect(kMaxExerciseTokenPrefix, 12);
    });

    test('the tokenizer agrees with the food platform, by design', () {
      // One proven implementation, two consoles. If these ever diverge it is a
      // bug in one of them, not a feature.
      expect(exerciseNameKey('Café Latte'), 'cafe latte');
    });
  });

  group('category vocabulary — parity with the backend', () {
    test('the taxonomy is exactly the 20 categories the server accepts', () {
      expect(kExerciseCategories, hasLength(20));
      expect(kExerciseCategories.toSet(), hasLength(20));
      expect(kExerciseCategories, const [
        'Chest', 'Back', 'Shoulders', 'Legs', 'Arms', 'Core', 'Cardio',
        'Mobility', 'Stretching', 'Olympic', 'Bodyweight', 'Machines', 'Cable',
        'Dumbbells', 'Barbell', 'Kettlebell', 'Bands', 'Functional',
        'Plyometric', 'Rehabilitation',
      ]);
    });
  });

  group('GlobalExerciseModel reads the catalog schema', () {
    test('a full document parses into every field', () {
      final e = GlobalExerciseModel.fromMap(const {
        'scope': 'global',
        'adminId': '',
        'name': 'Barbell Bench Press',
        'nameLower': 'barbell bench press',
        'category': 'Chest',
        'videoUrl': 'https://example.com/v.mp4',
        'isActive': true,
        'revision': 3,
        'source': 'seed',
        'aliases': ['Bench Press'],
        'equipment': 'Barbell',
        'videoDurationSec': 42,
      }, 'abc');

      expect(e.id, 'abc');
      expect(e.name, 'Barbell Bench Press');
      expect(e.category, 'Chest');
      expect(e.isActive, isTrue);
      expect(e.hasVideo, isTrue);
      expect(e.revision, 3);
      expect(e.aliases, ['Bench Press']);
      expect(e.videoDurationSec, 42);
      expect(e.hasUnknownCategory, isFalse);
    });

    test('no video is the ordinary state, not a parse failure', () {
      final e = GlobalExerciseModel.fromMap(const {'name': 'Plank'}, 'x');
      expect(e.videoUrl, '');
      expect(e.hasVideo, isFalse);
    });

    test('a whitespace-only video URL does not count as a video', () {
      final e = GlobalExerciseModel.fromMap(
        const {'name': 'Plank', 'videoUrl': '   '},
        'x',
      );
      expect(e.hasVideo, isFalse);
    });

    test('a document with no isActive field is LIVE, never invisible', () {
      // A row written before the field existed must not vanish from the
      // console's default view.
      final e = GlobalExerciseModel.fromMap(const {'name': 'Plank'}, 'x');
      expect(e.isActive, isTrue);
    });

    test('isActive false is respected', () {
      final e = GlobalExerciseModel.fromMap(
        const {'name': 'Plank', 'isActive': false},
        'x',
      );
      expect(e.isActive, isFalse);
    });

    test('a category outside the vocabulary is FLAGGED, not hidden', () {
      // The server refuses to create one, so seeing this means the vocabulary
      // moved underneath existing data. An unfilterable row must be visible.
      final e = GlobalExerciseModel.fromMap(
        const {'name': 'Sled Push', 'category': 'Sleds'},
        'x',
      );
      expect(e.hasUnknownCategory, isTrue);
    });

    test('an empty category is not reported as an unknown one', () {
      final e = GlobalExerciseModel.fromMap(const {'name': 'Plank'}, 'x');
      expect(e.hasUnknownCategory, isFalse);
    });

    test('garbage types do not throw — the console never crashes on a read', () {
      final e = GlobalExerciseModel.fromMap(const {
        'name': 42,
        'aliases': 'not a list',
        'revision': 'three',
        'videoDurationSec': {},
      }, 'x');
      expect(e.name, '42');
      expect(e.aliases, isEmpty);
      expect(e.revision, 1);
      expect(e.videoDurationSec, 0);
    });

    test('the callable payload omits every server-owned field', () {
      // A client that could set nameLower, searchTokens, scope or revision
      // could forge the catalog's identity and its duplicate key.
      final payload = const GlobalExerciseModel(
        id: 'abc',
        name: 'Plank',
        category: 'Core',
      ).toCallablePayload();

      expect(payload['id'], 'abc');
      expect(payload['name'], 'Plank');
      expect(payload.containsKey('nameLower'), isFalse);
      expect(payload.containsKey('searchTokens'), isFalse);
      expect(payload.containsKey('scope'), isFalse);
      expect(payload.containsKey('adminId'), isFalse);
      expect(payload.containsKey('revision'), isFalse);
      expect(payload.containsKey('createdAt'), isFalse);
      expect(payload.containsKey('isActive'), isFalse);
    });

    test('a create omits the id entirely rather than sending an empty one', () {
      final payload = const GlobalExerciseModel(
        id: '',
        name: 'Plank',
        category: 'Core',
      ).toCallablePayload();
      expect(payload.containsKey('id'), isFalse);
    });
  });

  group('import report accounting', () {
    test('a clean report accounts for every received row', () {
      const report = ExerciseImportReport(
        dryRun: true,
        received: 10,
        accepted: 10,
        imported: 0,
      );
      expect(report.isAccounted, isTrue);
      expect(report.isClean, isTrue);
      expect(report.willWrite, 10);
    });

    test('duplicates and rejects still add up to the received total', () {
      const report = ExerciseImportReport(
        dryRun: true,
        received: 10,
        accepted: 6,
        imported: 0,
        duplicates: [(name: 'Plank', reason: 'already in the catalog')],
        rejected: [
          (name: 'X', errors: ['name must be at least 2 characters']),
          (name: 'Y', errors: ['category']),
          (name: 'Z', errors: ['category']),
        ],
      );
      expect(report.isAccounted, isTrue);
      expect(report.isClean, isFalse);
    });

    test('a report that loses rows is DETECTED, not displayed as success', () {
      // The one thing an import summary must never hide is that the server and
      // the console disagree about what happened.
      const report = ExerciseImportReport(
        dryRun: false,
        received: 10,
        accepted: 4,
        imported: 4,
      );
      expect(report.isAccounted, isFalse);
    });

    test('update mode counts written rows across both buckets', () {
      const report = ExerciseImportReport(
        dryRun: false,
        conflictMode: 'update',
        received: 10,
        accepted: 4,
        willUpdate: 6,
        imported: 4,
        updated: 6,
      );
      expect(report.didWrite, 10);
      expect(report.isAccounted, isTrue);
    });
  });

  group('analytics', () {
    test('empty categories are named, so a gap is decidable', () {
      const a = ExerciseAnalytics(
        total: 3,
        categoryCounts: [
          ExerciseCategoryCount(category: 'Chest', count: 3, active: 3),
          ExerciseCategoryCount(category: 'Bands', count: 0),
        ],
      );
      expect(a.emptyCategories, ['Bands']);
    });

    test('inactive is derived per category rather than stored twice', () {
      const c = ExerciseCategoryCount(category: 'Chest', count: 10, active: 7);
      expect(c.inactive, 3);
      expect(c.isEmpty, isFalse);
    });
  });

  // ══════════════════════════════════════════════════════════════════════
  // THE SHIPPED DATASET
  // ══════════════════════════════════════════════════════════════════════

  group('the bundled master dataset would import cleanly', () {
    late CsvTable table;
    late List<Map<String, dynamic>> rows;

    setUpAll(() {
      // Read off disk rather than through rootBundle: this asserts the real
      // artifact that ships, not a copy of it.
      final file = File('assets/data/global_exercise_seed.csv');
      expect(
        file.existsSync(),
        isTrue,
        reason: 'The master dataset must ship at assets/data/'
            'global_exercise_seed.csv and be declared in pubspec.yaml.',
      );
      table = parseCsvTable(file.readAsStringSync());
      rows = csvToExerciseRows(table, mapExerciseCsvHeaders(table.headers));
    });

    test('it holds between 500 and 1000 exercises', () {
      expect(rows.length, greaterThanOrEqualTo(500));
      expect(rows.length, lessThanOrEqualTo(1000));
    });

    test('the header is exactly name and category — clean names only', () {
      expect(table.headers, ['name', 'category']);
      final mapping = mapExerciseCsvHeaders(table.headers);
      expect(unmappedCsvHeaders(table.headers, mapping), isEmpty);
    });

    test('every row has a name the server would accept', () {
      for (final row in rows) {
        final name = (row['name'] ?? '').toString().trim();
        expect(name.length, greaterThanOrEqualTo(2), reason: 'row: $row');
        expect(name.length, lessThanOrEqualTo(120), reason: name);
      }
    });

    test('every row sits in a real category', () {
      // A row in an unknown category is invisible in every filter, and the
      // server rejects it outright — so a single bad row would silently shrink
      // the import.
      for (final row in rows) {
        final category = (row['category'] ?? '').toString();
        expect(
          kExerciseCategories,
          contains(category),
          reason: '"${row['name']}" is filed under "$category"',
        );
      }
    });

    test('NOT ONE duplicate, by the server\'s own identity rule', () {
      // `exerciseNameKey` IS the duplicate key. Two rows that collapse to the
      // same key would import as one and silently shrink the catalog.
      final seen = <String, String>{};
      final collisions = <String>[];
      for (final row in rows) {
        final name = (row['name'] ?? '').toString();
        final key = exerciseNameKey(name);
        if (seen.containsKey(key)) {
          collisions.add('"$name" collides with "${seen[key]}"');
        }
        seen[key] = name;
      }
      expect(collisions, isEmpty);
      expect(seen.length, rows.length);
    });

    test('every one of the 20 categories is populated', () {
      // An empty category in the founding dataset is a gap nobody chose.
      final counts = <String, int>{};
      for (final row in rows) {
        final category = (row['category'] ?? '').toString();
        counts[category] = (counts[category] ?? 0) + 1;
      }
      for (final category in kExerciseCategories) {
        expect(
          counts[category] ?? 0,
          greaterThan(0),
          reason: '$category holds no exercises',
        );
      }
    });

    test('no row carries a video — the foundation ships names only', () {
      for (final row in rows) {
        expect(row.containsKey('videoUrl'), isFalse, reason: '${row['name']}');
      }
    });
  });
}
