import 'package:flutter_test/flutter_test.dart';
import 'package:alphaserena_admin_portel/core/utils/food_search.dart';
import 'package:alphaserena_admin_portel/models/global_food_model.dart';

// FOOD PLATFORM V1 — the console's half of the platform contract.
//
// The fixtures below were generated by running the backend's own
// `nameKey`/`searchPrefixFor` (functions/src/lib/food.ts). If either side
// drifts, the console would compute a prefix no stored document carries and
// report the global library as empty — so these are pinned, not derived.

void main() {
  group('search contract — parity with the backend', () {
    test('name keys match the backend exactly', () {
      expect(foodNameKey('Roti / Chapati (whole wheat)'), 'roti chapati whole wheat');
      expect(foodNameKey('Café Latte'), 'cafe latte');
      expect(foodNameKey('  Rolled   Oats  '), 'rolled oats');
      expect(foodNameKey('Dal'), 'dal');
    });

    test('query prefixes match the backend exactly', () {
      expect(foodSearchPrefix('chick'), 'chick');
      expect(foodSearchPrefix('CHICK'), 'chick');
      expect(foodSearchPrefix('  paneer masala '), 'paneer');
      // Longer than the stored prefix cap → truncated to it.
      expect(foodSearchPrefix('supercalifragilistic'), 'supercalifra');
    });

    test('a query below the minimum prefix is refused, not guessed', () {
      expect(foodSearchPrefix('a'), isNull);
      expect(foodSearchPrefix(''), isNull);
      expect(foodSearchPrefix('  '), isNull);
      expect(foodSearchPrefix('!!'), isNull);
      expect(kMinSearchPrefix, 2);
      expect(kMaxTokenPrefix, 12);
    });
  });

  group('GlobalFoodModel reads the canonical schema', () {
    test('a global food is recognised and carries an EMPTY owner', () {
      final f = GlobalFoodModel.fromMap(const {
        'scope': 'global',
        'adminId': '',
        'name': 'Rolled Oats',
        'status': 'active',
        'verification': 'official',
        'baseGrams': 100,
        'calories': 379,
        'protein': 13.2,
        'carbs': 67.7,
        'fat': 6.5,
        'portions': [
          {'label': 'cup', 'grams': 90},
        ],
      }, 'g-1');

      expect(f.isGlobal, isTrue);
      expect(f.adminId, '');
      expect(f.isOfficial, isTrue);
      expect(f.isArchived, isFalse);
      // The macros must survive: the orphan model this replaced read `fats`
      // and `baseQuantity` and would have zeroed every one of these.
      expect(f.protein, 13.2);
      expect(f.carbs, 67.7);
      expect(f.fat, 6.5);
      expect(f.portions.single.label, 'cup');
      expect(f.portions.single.grams, 90);
    });

    test('a pre-V1 organization document reads as an active org food', () {
      final f = GlobalFoodModel.fromMap(const {
        'name': 'Idli',
        'adminId': 'org-1',
        'calories': 130,
      }, 'legacy-1');

      expect(f.isGlobal, isFalse);
      expect(f.scope, 'org');
      expect(f.isArchived, isFalse);
      expect(f.verification, 'unverified');
      expect(f.baseGrams, isNull); // legacy per-serving, not per-100 g
    });

    test('an archived food stays fully readable so plans keep resolving', () {
      final f = GlobalFoodModel.fromMap(const {
        'scope': 'global',
        'name': 'Retired',
        'status': 'archived',
        'calories': 200,
      }, 'x');
      expect(f.isArchived, isTrue);
      expect(f.calories, 200);
    });

    test('the Atwater estimate exposes an implausible row', () {
      final bogus = GlobalFoodModel.fromMap(const {
        'scope': 'global',
        'name': 'Bogus',
        'calories': 900,
        'protein': 1,
        'carbs': 1,
        'fat': 1,
      }, 'x');
      expect(bogus.energyFromMacros, 17);
      expect((bogus.calories - bogus.energyFromMacros).abs() > 50, isTrue);
    });

    test('the callable payload never carries stored-only fields', () {
      final payload = GlobalFoodModel.fromMap(const {
        'scope': 'global',
        'name': 'Oats',
        'status': 'archived',
        'revision': 7,
        'calories': 379,
      }, 'g-1').toCallablePayload();

      // status, revision and scope are SERVER-owned: the console must not be
      // able to set them by smuggling them into an upsert payload.
      expect(payload.containsKey('status'), isFalse);
      expect(payload.containsKey('revision'), isFalse);
      expect(payload.containsKey('scope'), isFalse);
      expect(payload.containsKey('verification'), isFalse);
      expect(payload['id'], 'g-1');
      expect(payload['calories'], 379);
    });
  });
}
